List data = [
  {
    "productId": "L-1001",
    "brand": "lenovo",
    "description": "Keyboard",
    "purchaseDate": "01/01/2020",
    "category": "HP",
    "model": "thinkbook g4",
    "serialNumber": "MP24C06F",
    "cost": "8000.0",
    "assignedTo": "NA",
    "lastScanDate": "03/20/2024",
    "dueDate": "NA",
    "disposeDate": "NA",
    "createdDate": "03/20/2024",
    "site": "Lahore Office",
    "location": "HAFIZ CENTER",
    "depreciation": "Yes",
    "depreciationMethod": "Sum of the Years Digits",
    "totalCost": "99",
    "assetLife": "66",
    "salvageValue": "99",
    "dateAquired": "04/16/2024",
    "img": 'assets/images/logos/key.jpeg'
  },
  {
    "productId": "AH-01",
    "brand": "Apple",
    "description": "Iphone",
    "purchaseDate": "01/04/2024",
    "category": "Electronics",
    "model": "0001F4",
    "serialNumber": "MP24C06F",
    "cost": "8000.0",
    "assignedTo": "NA",
    "lastScanDate": "03/20/2024",
    "dueDate": "NA",
    "disposeDate": "NA",
    "createdDate": "03/20/2024",
    "site": "Lahore Office",
    "location": "Islamabad",
    "depreciation": "Yes",
    "depreciationMethod": "Sum of the Years Digits",
    "totalCost": "99",
    "assetLife": "66",
    "salvageValue": "99",
    "dateAquired": "04/16/2024",
    "img": 'assets/images/logos/iphone.jpeg'
  },
  {
    "productId": "5-99-a",
    "brand": "Dell",
    "description": "Mouse",
    "purchaseDate": "01/01/2020",
    "category": "NA",
    "model": "PRO",
    "serialNumber": "MP24C06F",
    "cost": "8000.0",
    "assignedTo": "NA",
    "lastScanDate": "03/20/2024",
    "dueDate": "NA",
    "disposeDate": "NA",
    "createdDate": "03/20/2024",
    "site": "Lahore Office",
    "location": "Faislabad",
    "depreciation": "Yes",
    "depreciationMethod": "Sum of the Years Digits",
    "totalCost": "99",
    "assetLife": "66",
    "salvageValue": "99",
    "dateAquired": "04/16/2024",
    "img": 'assets/images/logos/mous.jpeg'
  },
  {
    "productId": "54-uy",
    "brand": "lenovo",
    "description": "Laptop",
    "purchaseDate": "01/01/2020",
    "category": "NA",
    "model": "PRO",
    "serialNumber": "MP24C06F",
    "cost": "8000.0",
    "assignedTo": "NA",
    "lastScanDate": "03/20/2024",
    "dueDate": "NA",
    "disposeDate": "NA",
    "createdDate": "03/20/2024",
    "site": "Lahore Office",
    "location": "Faislabad",
    "depreciation": "Yes",
    "depreciationMethod": "Sum of the Years Digits",
    "totalCost": "99",
    "assetLife": "66",
    "salvageValue": "99",
    "dateAquired": "04/16/2024",
    "img": 'assets/images/logos/ll.jpeg'
  },
  {
    "productId": "541521-u",
    "brand": "DC-Inverter",
    "description": "AC",
    "purchaseDate": "01/01/2020",
    "category": "NA",
    "model": "PRO",
    "serialNumber": "MP24C06F",
    "cost": "8000.0",
    "assignedTo": "NA",
    "lastScanDate": "03/20/2024",
    "dueDate": "NA",
    "disposeDate": "NA",
    "createdDate": "03/20/2024",
    "site": "Lahore Office",
    "location": "Faislabad",
    "depreciation": "Yes",
    "depreciationMethod": "Sum of the Years Digits",
    "totalCost": "99",
    "assetLife": "66",
    "salvageValue": "99",
    "dateAquired": "04/16/2024",
    "img": 'assets/images/logos/ac.jpeg'
  }
];
